select * 
from HR.Employees
where LastName like 'A%'

USE [test]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [IX_HREmployees_LastName] ON [HR].[Employees]
(
	[LastName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

USE [test]

GO

ALTER INDEX [IX_HREmployees_LastName] ON [HR].[Employees] REBUILD PARTITION = ALL WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)

GO


USE [test]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [IX_HREmployees_LastName] ON [HR].[Employees]
(
	[LastName] ASC,
	[FirstName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

